// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/showtime.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/showtime.go -destination=internal/mock/mock_showtime_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/firmanains/cinema-ticketing/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShowtimeRepository is a mock of ShowtimeRepository interface.
type MockShowtimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShowtimeRepositoryMockRecorder
	isgomock struct{}
}

// MockShowtimeRepositoryMockRecorder is the mock recorder for MockShowtimeRepository.
type MockShowtimeRepositoryMockRecorder struct {
	mock *MockShowtimeRepository
}

// NewMockShowtimeRepository creates a new mock instance.
func NewMockShowtimeRepository(ctrl *gomock.Controller) *MockShowtimeRepository {
	mock := &MockShowtimeRepository{ctrl: ctrl}
	mock.recorder = &MockShowtimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowtimeRepository) EXPECT() *MockShowtimeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShowtimeRepository) Create(ctx context.Context, showtime *domain.Showtime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, showtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShowtimeRepositoryMockRecorder) Create(ctx, showtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShowtimeRepository)(nil).Create), ctx, showtime)
}

// Delete mocks base method.
func (m *MockShowtimeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShowtimeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShowtimeRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockShowtimeRepository) FindAll(ctx context.Context, page, limit int) ([]domain.Showtime, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, page, limit)
	ret0, _ := ret[0].([]domain.Showtime)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShowtimeRepositoryMockRecorder) FindAll(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShowtimeRepository)(nil).FindAll), ctx, page, limit)
}

// FindByID mocks base method.
func (m *MockShowtimeRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Showtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Showtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShowtimeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShowtimeRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockShowtimeRepository) Update(ctx context.Context, id uuid.UUID, req domain.UpdateShowtimeRequest) (*domain.Showtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*domain.Showtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockShowtimeRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShowtimeRepository)(nil).Update), ctx, id, req)
}
