// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/refresh_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/refresh_token.go -destination=internal/mock/mock_refresh_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/firmanains/cinema-ticketing/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// FindByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByTokenHash), ctx, tokenHash)
}

// RevokeByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) RevokeByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByTokenHash indicates an expected call of RevokeByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeByTokenHash), ctx, tokenHash)
}

// Store mocks base method.
func (m *MockRefreshTokenRepository) Store(ctx context.Context, token *domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRefreshTokenRepositoryMockRecorder) Store(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Store), ctx, token)
}
