// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/showtime.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/showtime.go -destination=internal/mock/mock_showtime_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/firmanains/cinema-ticketing/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockShowtimeService is a mock of ShowtimeService interface.
type MockShowtimeService struct {
	ctrl     *gomock.Controller
	recorder *MockShowtimeServiceMockRecorder
	isgomock struct{}
}

// MockShowtimeServiceMockRecorder is the mock recorder for MockShowtimeService.
type MockShowtimeServiceMockRecorder struct {
	mock *MockShowtimeService
}

// NewMockShowtimeService creates a new mock instance.
func NewMockShowtimeService(ctrl *gomock.Controller) *MockShowtimeService {
	mock := &MockShowtimeService{ctrl: ctrl}
	mock.recorder = &MockShowtimeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowtimeService) EXPECT() *MockShowtimeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShowtimeService) Create(ctx context.Context, req domain.CreateShowtimeRequest) (*domain.Showtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.Showtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShowtimeServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShowtimeService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockShowtimeService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShowtimeServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShowtimeService)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockShowtimeService) GetAll(ctx context.Context, page, limit int) (*domain.PaginatedResult[domain.Showtime], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, limit)
	ret0, _ := ret[0].(*domain.PaginatedResult[domain.Showtime])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockShowtimeServiceMockRecorder) GetAll(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockShowtimeService)(nil).GetAll), ctx, page, limit)
}

// GetByID mocks base method.
func (m *MockShowtimeService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Showtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Showtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShowtimeServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShowtimeService)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockShowtimeService) Update(ctx context.Context, id uuid.UUID, req domain.UpdateShowtimeRequest) (*domain.Showtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*domain.Showtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockShowtimeServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShowtimeService)(nil).Update), ctx, id, req)
}
